### ISSUE TITLE
Linkedin Link can't create page

### ISSUE THREAD

**Issue by sadiqueali786** [mviniciusca/warriorfolio#1]
Can't create page because of linkedin page link. 
![Screenshot 2023-08-30 003843](https://github.com/mviniciusca/warriorfolio/assets/60964121/76ed2124-f3b0-4b88-84f2-0c4113e0443d)

**Comment by mviniciusca** [comment]
Did you run the database seed? It's necessary to execute the command "php artisan migrate:fresh --seed" before starting the page creation process! This will preload the default values into the database.
