### ISSUE TITLE
Quando está em modo produção, dá erro 403 mesmo quando faço login mesmo com o email verificado

### ISSUE THREAD

**Issue by gilmarodp** [mviniciusca/warriorfolio#4]

**Comment by mviniciusca** [comment]
Bom dia,

Estou de férias e longe do PC por uns dias, estou te respondendo pelo meu
celular. Vamos lá:

Quando se coloca em produção, de acordo com a documentação do Filament é
necessário implementar um novo contrato para o acesso ao painel com o seu
email.

Segue o link da documentação:

https://filamentphp.com/community/danharrin-panel-403-in-production

E aqui:

https://filamentphp.com/docs/3.x/panels/users/#authorizing-access-to-the-panel


Me desculpa por responder assim.
Tenha um bom dia!

Marcos.




Em dom., 26 de nov. de 2023 18:35, Gilmar Oliveira ***@***.***>
escreveu:
